apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../_base/nginx.yaml
- nginx-busy.yaml
patches:
- target:
    name: nginx
  path: nginx-overlays.yaml
images:
- name: public.ecr.aws/nginx/nginx
  newTag: 1.27.2
