apiVersion: v1
kind: Pod
metadata:
  #annotations:
    #argocd.argoproj.io/hook: PreSync
  name: sleep-pod
spec:
  containers:
    - name: sleep-container
      image: busybox       # Utilise une image légère avec la commande `sleep`
      command: ["sleep", "6"]
  restartPolicy: Never     # Empêche le redémarrage automatique après la fin des 6 secondes