apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-two
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:MatClt/argocd-demo.git
    targetRevision: "main"
    path: "app/two"

  destination:
    server: https://kubernetes.default.svc
    namespace: two

  # Extra information to show in the Argo CD Application details tab
  info:
    - name: 'Example:'
      value: 'https://example.com'

  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
      - FailOnSharedResource=true
